sudo: required
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5

language: node_js

node_js:
  - 6
  - 5
  - 4

os:
  - linux
  - osx

env:
  global:
    - CC=gcc-5 CXX=g++-5

before_install:
  - npm install -g npm@latest

script:
  - ./node_modules/.bin/gulp ci

deploy:
  provider: npm
  email: piotr.baranowski@zaklinaczekodu.com
  api_key: $NPM_API_KEY
  on:
    node: 6
    condition: $TRAVIS_OS_NAME == linux
    tags: true
    repo: refilljs/refill-node