addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5

language: node_js

node_js:
  - 5
  - 4
  - 0.12
  - 0.10

os:
  - linux

env:
  global:
    - CC=gcc-5 CXX=g++-5

before_install:
  - npm config set progress false
  - npm install -g npm@latest

script:
  - ./node_modules/.bin/gulp ci

deploy:
  provider: npm
  email: piotr.baranowski@zaklinaczekodu.com
  api_key: $NPM_API_KEY
  on:
    node: 5
    tags: true
    repo: zaklinaczekodu/zkflow-node